<?php

$GLOBALS['ROOT'] =$_SERVER['DOCUMENT_ROOT']."PWD/";

// FUNCIONES data_submitted Y spl_autoload_register
// TAMBIÉN FUNCIONES QUE USAN LA LIBRERIA PHPMailer
// CREA INSTANCIA DE LA LIBRERIA PHPAuth Y LA CONECTA CON LA BASE DE DATOS
include_once("Utiles/funciones.php");

// ENCONTRARÁN LAS CONSULTAS SQL PARA GENERAR LAS TABLAS EN LA CARPETA "database" (ESTO VIENE CON LA LIBRERIA)

//MODIFICAR SEGÚN TENGAS EL PROYECTO

$PROYECTO ='PWD\TP-Final-PWD';

//variable que almacena el directorio del proyecto
$ROOT =$_SERVER['DOCUMENT_ROOT']."/$PROYECTO/";

?>